/-
Copyright (c) 2026 Colin Defant. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Colin Defant
-/
module

public import CycleCutoff.Cycle.Defs
public import CycleCutoff.Generator.SemigroupLower
public import CycleCutoff.Generator.SemigroupRowsum
public import Mathlib.GroupTheory.Perm.Sign
public import Mathlib.Data.ZMod.Basic

/-!
# Positivity of the law of the cycle shuffle

For `t > 0` and every permutation `σ` of `ℤ/nℤ`, the law `μ_t(σ) = P_t(id, σ)` of the adjacent
transposition shuffle on the cycle is positive. The law `μ_t` is also a probability vector for
`t ≥ 0` and satisfies `μ_{t+s} = μ_t P_s`.

## Main results

* `CycleCutoff.InvFamily.exists_one_le_pow_apply_of_mem_closure`: for an involution family
  whose maps are left multiplications `T_e ρ = g_e ρ` on a monoid, every element `σ` of the
  submonoid generated by the `g_e` has `((Q_𝒯 + |I| I)^k)(1, σ) ≥ 1` for some `k`.
* `CycleCutoff.mclosure_swap_add_one`: the transpositions `(x  x+1)`, `x ∈ ℤ/nℤ`, generate
  the symmetric group on `ℤ/nℤ` as a monoid.
* `CycleCutoff.muT_pos`: `μ_t(σ) > 0` for `t > 0`.
* `CycleCutoff.isProbVec_muT`, `CycleCutoff.muT_eq_single_vecMul`, `CycleCutoff.muT_add`: `μ_t` is
  a probability vector, the row `1` of `P_t`, and `μ_{t+s} = μ_t P_s`.
-/

public section

open Finset Matrix Equiv

namespace CycleCutoff

namespace InvFamily

variable {ι Ω : Type*} [Fintype ι] [Fintype Ω] [DecidableEq Ω] (𝒯 : InvFamily ι Ω)

/-- If `((Q_𝒯 + |I| I)^k)(z, w) ≥ 1`, then `((Q_𝒯 + |I| I)^(k+1))(z, T_e w) ≥ 1`. -/
theorem one_le_pow_succ_apply_T {k : ℕ} {z w : Ω}
    (h : 1 ≤ ((𝒯.rateMatrix + (Fintype.card ι : ℝ) • (1 : Matrix Ω Ω ℝ)) ^ k) z w) (e : ι) :
    1 ≤ ((𝒯.rateMatrix + (Fintype.card ι : ℝ) • (1 : Matrix Ω Ω ℝ)) ^ (k + 1)) z (𝒯.T e w) := by
  have hMw : 1 ≤ (𝒯.rateMatrix + (Fintype.card ι : ℝ) • (1 : Matrix Ω Ω ℝ)) w (𝒯.T e w) := by
    rw [rateMatrix_add_card_smul_one_apply]
    exact_mod_cast Finset.card_pos.mpr ⟨e, by simp⟩
  set M := 𝒯.rateMatrix + (Fintype.card ι : ℝ) • (1 : Matrix Ω Ω ℝ)
  have hM : ∀ a b, 0 ≤ M a b := 𝒯.rateMatrix_add_card_smul_one_apply_nonneg
  rw [pow_succ, mul_apply]
  calc (1 : ℝ) ≤ (M ^ k) z w * M w (𝒯.T e w) := one_le_mul_of_one_le_of_one_le h hMw
    _ ≤ ∑ j, (M ^ k) z j * M j (𝒯.T e w) :=
      Finset.single_le_sum (f := fun j => (M ^ k) z j * M j (𝒯.T e w))
        (fun j _ => mul_nonneg (pow_apply_nonneg hM k z j) (hM j _)) (Finset.mem_univ w)

/-- For an involution family on a monoid whose maps are left multiplications `T_e ρ = g_e ρ`,
every element `σ` of the submonoid generated by the `g_e` satisfies
`((Q_𝒯 + |I| I)^k)(1, σ) ≥ 1` for some `k`. -/
theorem exists_one_le_pow_apply_of_mem_closure [Monoid Ω] {g : ι → Ω}
    (hg : ∀ e ρ, 𝒯.T e ρ = g e * ρ) {σ : Ω} (hσ : σ ∈ Submonoid.closure (Set.range g)) :
    ∃ k : ℕ, 1 ≤ ((𝒯.rateMatrix + (Fintype.card ι : ℝ) • (1 : Matrix Ω Ω ℝ)) ^ k) 1 σ := by
  induction hσ using Submonoid.closure_induction_left with
  | one => exact ⟨0, by simp⟩
  | mul_left x hx y _ ih =>
    obtain ⟨e, rfl⟩ := hx
    obtain ⟨k, hk⟩ := ih
    exact ⟨k + 1, hg e y ▸ 𝒯.one_le_pow_succ_apply_T hk e⟩

end InvFamily

/-- The transpositions `(x  x+1)`, `x ∈ ℤ/nℤ`, generate the symmetric group on `ℤ/nℤ` as a
monoid. -/
theorem mclosure_swap_add_one (n : ℕ) [NeZero n] :
    Submonoid.closure (Set.range fun x : ZMod n => swap x (x + 1)) = ⊤ := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (NeZero.ne n)
  let e : Fin (k + 1) ≃ ZMod (k + 1) := (ZMod.finEquiv (k + 1)).toEquiv
  refine top_unique fun σ _ => ?_
  have hmem : e.permCongrHom.symm σ ∈
      Submonoid.closure (Set.range fun i : Fin k => swap i.castSucc i.succ) := by
    rw [Perm.mclosure_swap_castSucc_succ]; trivial
  have := Submonoid.mem_map_of_mem e.permCongrHom hmem
  rw [MonoidHom.map_mclosure, MulEquiv.apply_symm_apply] at this
  refine Submonoid.closure_mono ?_ this
  rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
  refine ⟨e i.castSucc, ?_⟩
  simp only [permCongrHom_coe, permCongr_def, symm_trans_swap_trans]
  congr 1
  change ZMod.finEquiv (k + 1) i.castSucc + 1 = ZMod.finEquiv (k + 1) i.succ
  rw [← Fin.coeSucc_eq_succ, map_add, map_one]

variable {n : ℕ} [NeZero n]

/-- **Positivity of the law.** For `t > 0`, the law `μ_t` of the adjacent transposition shuffle
on the cycle charges every permutation: `μ_t(σ) > 0`. -/
@[cycle_cutoff "lem_mu_positive"]
theorem muT_pos {t : ℝ} (ht : 0 < t) (σ : Perm (ZMod n)) : 0 < muT n t σ := by
  obtain ⟨k, hk⟩ := (cycleShuffle n).exists_one_le_pow_apply_of_mem_closure
    (g := fun x : ZMod n => swap x (x + 1)) (fun _ _ => rfl)
    (σ := σ) (by rw [mclosure_swap_add_one]; trivial)
  rw [muT_def]
  refine lt_of_lt_of_le ?_ ((cycleShuffle n).exp_mul_pow_le_semigroup ht.le k 1 σ)
  positivity

/-! ### The law `μ_t` as a probability vector and as a row of the semigroup -/

/-- The law of the shuffle at time `t ≥ 0` is non-negative. -/
theorem muT_nonneg {t : ℝ} (ht : 0 ≤ t) (σ : Perm (ZMod n)) : 0 ≤ muT n t σ :=
  (cycleShuffle n).semigroup_apply_nonneg ht 1 σ

/-- The law `μ_t` has total mass one. -/
theorem sum_muT (t : ℝ) : ∑ σ, muT n t σ = 1 :=
  (cycleShuffle n).sum_semigroup_apply t 1

/-- The law `μ_t` of the shuffle is a probability vector for `t ≥ 0`. -/
theorem isProbVec_muT {t : ℝ} (ht : 0 ≤ t) : IsProbVec (muT n t) :=
  ⟨muT_nonneg ht, sum_muT t⟩

/-- The law `μ_t` is row `1` of the semigroup `P_t`. -/
theorem muT_eq_single_vecMul (t : ℝ) :
    muT n t = vecMul (Pi.single 1 1 : Perm (ZMod n) → ℝ) ((cycleShuffle n).semigroup t) := by
  funext σ
  simp [vecMul, dotProduct, Pi.single_apply, muT_def]

/-- The semigroup property along the law: `μ_{t + s} = μ_t P_s`. -/
theorem muT_add (t s : ℝ) : muT n (t + s) = muT n t ᵥ* (cycleShuffle n).semigroup s := by
  rw [muT_eq_single_vecMul, muT_eq_single_vecMul, vecMul_vecMul]
  congr 1
  exact semigroup_add _ t s

end CycleCutoff
